# Generated by Django 5.0.6 on 2024-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Precio', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
