# Generated by Django 5.0.6 on 2024-07-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_producto_imagen_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('apellidoUsuario', models.CharField(max_length=20)),
                ('contraUsuario', models.CharField(max_length=20)),
                ('correoUsuario', models.EmailField(max_length=20)),
            ],
        ),
    ]
